import type { Metadata } from "next";
import { 
  PageContainer, 
  PageHeader, 
  Section, 
  Footer 
} from "@/components/ui/EnhancedLayouts";
import { generatePageMetadata } from "@/components/ui/EnhancedLayouts";
import Link from "next/link";

export const metadata: Metadata = generatePageMetadata({
  title: "Disclaimer – RealMoneyCalc | Legal Information & Important Terms",
  description: "Important disclaimers and legal information for RealMoneyCalc financial calculators. Understand the limitations and proper use of our inflation-adjusted planning tools.",
  keywords: ["disclaimer", "legal", "terms of use", "financial calculator disclaimer", "investment risks"],
  path: "/disclaimer",
});

export default function DisclaimerPage() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "name": "Disclaimer",
    "description": "Legal disclaimers and terms of use for RealMoneyCalc financial planning tools",
    "url": "https://realmoneycalc.com/disclaimer",
    "publisher": {
      "@type": "Organization",
      "name": "RealMoneyCalc"
    }
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      
      <PageContainer maxWidth="lg">
        {/* Header with Logo */}
        <div className="text-center pt-6 pb-2">
          <Link href="/" className="inline-block hover:scale-105 transition-transform duration-200">
            <img 
              src="/logo.png" 
              alt="RealMoneyCalc" 
              className="w-24 h-24 sm:w-28 sm:h-28 mx-auto drop-shadow-xl"
              width="112"
              height="112"
              loading="eager"
              decoding="sync"
            />
          </Link>
        </div>

        <PageHeader
          title="Disclaimer"
          description="Important legal information and terms of use"
          breadcrumb={[
            { label: 'Home', href: '/' },
            { label: 'Disclaimer', href: '/disclaimer' }
          ]}
        />

        {/* Main Content */}
        <Section background="card" padding="lg">
          <div className="prose prose-lg max-w-none dark:prose-invert">
            
            {/* Last Updated */}
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-6 font-medium">
              Last Updated: February 2026
            </p>

            {/* Introduction */}
            <div className="mb-8">
              <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                The information and calculators provided on <strong>RealMoneyCalc</strong> (https://realmoneycalc.com) are for educational and informational purposes only. By using this website, you agree to the terms of this disclaimer.
              </p>
            </div>

            {/* 1. Not Financial Advice */}
            <div className="mb-8">
              <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
                <span>⚖️</span>
                1. Not Financial Advice
              </h3>
              <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                The developer of RealMoneyCalc is not a SEBI-registered financial advisor, certified financial planner, or tax professional. The results generated by our calculators are estimates based on user-provided inputs and mathematical formulas. They should not be construed as professional financial, investment, or legal advice.
              </p>
            </div>

            {/* 2. Accuracy of Information */}
            <div className="mb-8">
              <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
                <span>📊</span>
                2. Accuracy of Information
              </h3>
              <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                While we strive to ensure the mathematical accuracy of our tools, financial markets and inflation rates are unpredictable. Past performance is not indicative of future results. RealMoneyCalc does not guarantee the accuracy, completeness, or reliability of any calculation or data point provided.
              </p>
            </div>

            {/* 3. Investment Risks */}
            <div className="mb-8">
              <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
                <span>⚠️</span>
                3. Investment Risks
              </h3>
              <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                Mutual fund investments are subject to market risks. Please read all scheme-related documents carefully before investing. RealMoneyCalc is not responsible for any financial losses or decisions made based on the results of our calculators.
              </p>
            </div>

            {/* 4. Third-Party Links */}
            <div className="mb-8">
              <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
                <span>🔗</span>
                4. Third-Party Links
              </h3>
              <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                Our website may contain links to external sites. We do not endorse or take responsibility for the content or practices of these third-party websites.
              </p>
            </div>

            {/* Important Notice */}
            <div className="bg-amber-50 dark:bg-amber-900/20 border-l-4 border-amber-400 p-6 rounded-r-lg">
              <p className="text-amber-800 dark:text-amber-300 font-medium italic">
                Always consult with a qualified financial professional before making significant investment decisions.
              </p>
            </div>

          </div>
        </Section>

        {/* Footer */}
        <Footer />
      </PageContainer>
    </>
  );
}